#!/usr/bin/env python3
"""
plot_circle_traj.py — Circular Trajectory Data Visualization
=========================================================
Usage:
  python3 plot_circle_traj.py <csv_file> [output_png]

Input:
  csv_file   — CSV file generated by circle_controller
               (default: /tmp/circle_traj_data.csv)

Output:
  output_png — Output path for the plot (default: /tmp/circle_traj_plot.png)

Plot layout:
  3 rows x N columns (N = number of joints):
    Row 1: Position (rad)
    Row 2: Velocity (rad/s)
    Row 3: Acceleration (rad/s²)
=========================================================
"""

import sys
import os
import csv
import math
import matplotlib
matplotlib.use("Agg")  # works without a display
import matplotlib.pyplot as plt
from matplotlib import font_manager

# ── Font configuration ──
plt.rcParams["font.family"] = "DejaVu Sans"
plt.rcParams["axes.unicode_minus"] = False  # render minus sign correctly
import matplotlib.ticker as ticker
import numpy as np

# ──────────────────────────────────────────
# Parse command-line arguments
# ──────────────────────────────────────────
csv_path    = sys.argv[1] if len(sys.argv) > 1 else "/tmp/circle_traj_data.csv"
output_path = sys.argv[2] if len(sys.argv) > 2 else "/tmp/circle_traj_plot.png"

if not os.path.isfile(csv_path):
    print(f"[ERROR] CSV file not found: {csv_path}", file=sys.stderr)
    sys.exit(1)

# ──────────────────────────────────────────
# Read CSV data
# ──────────────────────────────────────────
with open(csv_path, newline="") as f:
    reader = csv.DictReader(f)
    headers = reader.fieldnames  # ['time', 'j1_pos', 'j1_vel', 'j1_acc', ...]
    rows = [row for row in reader]

if not rows:
    print(f"[ERROR] CSV file is empty: {csv_path}", file=sys.stderr)
    sys.exit(1)

# Parse joint names (strip _pos/_vel/_acc suffixes, extract unique joint names)
joint_names = []
seen = set()
for h in headers:
    if h == "time":
        continue
    base = h.rsplit("_", 1)[0]
    if base not in seen:
        seen.add(base)
        joint_names.append(base)

n_joints = len(joint_names)
print(f"[INFO] Read {len(rows)} waypoints / {n_joints} joints: {joint_names}")

# Extract time series
time = np.array([float(r["time"]) for r in rows])

# Extract per-joint data
data = {}
for jn in joint_names:
    data[jn] = {
        "pos": np.array([float(r.get(f"{jn}_pos", 0)) for r in rows]),
        "vel": np.array([float(r.get(f"{jn}_vel", 0)) for r in rows]),
        "acc": np.array([float(r.get(f"{jn}_acc", 0)) for r in rows]),
    }

# ──────────────────────────────────────────
# Color scheme (one color per joint)
# ──────────────────────────────────────────
COLORS = [
    "#4C72B0",  # blue
    "#DD8452",  # orange
    "#55A868",  # green
    "#C44E52",  # red
    "#8172B3",  # purple
    "#937860",  # brown
    "#DA8BC3",  # pink
    "#8C8C8C",  # gray
]

# ──────────────────────────────────────────
# Layout: 3 rows (pos/vel/acc) x n_joints columns
# ──────────────────────────────────────────
ROW_LABELS = ["Position (rad)", "Velocity (rad/s)", "Acceleration (rad/s²)"]
ROW_KEYS   = ["pos", "vel", "acc"]
FIG_W      = max(6 * n_joints, 12)
FIG_H      = 12

fig, axes = plt.subplots(
    nrows=3,
    ncols=n_joints,
    figsize=(FIG_W, FIG_H),
    sharex=True,
    squeeze=False,
)

fig.suptitle(
    f"Circular Trajectory Analysis — TOTG Time Parameterization\n"
    f"{n_joints} joints / {len(rows)} waypoints / total duration {time[-1]:.2f} s",
    fontsize=14,
    fontweight="bold",
    y=1.01,
)

for col, jn in enumerate(joint_names):
    color = COLORS[col % len(COLORS)]
    for row, (key, ylabel) in enumerate(zip(ROW_KEYS, ROW_LABELS)):
        ax = axes[row][col]
        y = data[jn][key]

        ax.plot(time, y, color=color, linewidth=1.4, label=jn)
        ax.axhline(0, color="gray", linewidth=0.5, linestyle="--", alpha=0.6)

        # Annotate max/min values
        ymax, ymin = y.max(), y.min()
        ax.axhline(ymax, color=color, linewidth=0.8, linestyle=":", alpha=0.7)
        ax.axhline(ymin, color=color, linewidth=0.8, linestyle=":", alpha=0.7)
        ax.text(
            time[-1], ymax, f" {ymax:.3f}",
            va="bottom", ha="right", fontsize=7, color=color,
        )
        ax.text(
            time[-1], ymin, f" {ymin:.3f}",
            va="top", ha="right", fontsize=7, color=color,
        )

        # Axis labels
        if col == 0:
            ax.set_ylabel(ylabel, fontsize=9)
        if row == 0:
            ax.set_title(jn, fontsize=10, fontweight="bold", color=color)
        if row == 2:
            ax.set_xlabel("Time (s)", fontsize=9)

        ax.grid(True, which="major", alpha=0.35, linestyle="--")
        ax.grid(True, which="minor", alpha=0.15, linestyle=":")
        ax.minorticks_on()
        ax.yaxis.set_major_formatter(ticker.FormatStrFormatter("%.2f"))
        ax.tick_params(labelsize=8)

# ──────────────────────────────────────────
# Add summary statistics text box (bottom)
# ──────────────────────────────────────────
stats_lines = ["Joint Statistics Summary:"]
for jn in joint_names:
    pmax = data[jn]["pos"].max()
    pmin = data[jn]["pos"].min()
    vmax = abs(data[jn]["vel"]).max()
    amax = abs(data[jn]["acc"]).max()
    stats_lines.append(
        f"  {jn}: pos∈[{math.degrees(pmin):.1f}°,{math.degrees(pmax):.1f}°]"
        f"  vmax={math.degrees(vmax):.1f}°/s"
        f"  amax={math.degrees(amax):.1f}°/s²"
    )
stats_text = "\n".join(stats_lines)
fig.text(
    0.5, -0.01,
    stats_text,
    ha="center", va="top",
    fontsize=8,
    family="monospace",
    bbox=dict(boxstyle="round,pad=0.4", facecolor="#F5F5F5", alpha=0.8, edgecolor="#CCCCCC"),
)

plt.tight_layout()
plt.savefig(output_path, dpi=150, bbox_inches="tight")
print(f"[INFO] Plot saved to: {output_path}")
