<?xml version="1.0"?>
<!--
  Copyright (c) 2025. Muzixiaowen(xin.li at switchpi.com) All rights reserved.
  For more details, check out in https://gitee.com/switchpi/dummyx2
-->
<package format="3">
  <name>dummyx_usb2can</name>
  <version>0.1.0</version>
  <description>A dummy USB to CAN interface node for ROS2</description>
  <maintainer email="your.email@example.com">Your Name</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>